name: "dart_simple_live"
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: |
        tag=$(cat version.json | jq  ".dart_simple_live")
        latest_tag=$(curl -s https://api.github.com/repos/xiaoyaocz/dart_simple_live/releases/latest | jq  '.tag_name | ltrimstr("v")')

        echo "dart_simple_live version: $tag/$latest_tag"

        if [ "$tag" != "$latest_tag" ]; then
          echo "dart_simple_live version is outdated. Updating..."

          cat apps.json | jq --arg latest_tag "$latest_tag" '.apps += [{
            "name": "dart_simple_live",
            "bundleIdentifier": "com.xycz.simple-live",
            "iconURL": "https://github.com/xiaoyaocz/dart_simple_live/blob/master/assets/logo.png?raw=true",
            "downloadURL": "https://github.com/xiaoyaocz/dart_simple_live/releases/download/v\($latest_tag)/ios_no_sign.ipa",
            "version": $latest_tag
          }]'  > apps.json

          cat version.json | jq --arg latest_tag "$latest_tag" '.dart_simple_live = $latest_tag' > version.json

        else
          echo "dart_simple_live version is up to date."
        fi

        
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        if git diff --quiet; then
          echo "No changes to commit."
        else
          git add .
          git commit -m "update app"
          git push
        fi
