name: "PiliPlus"
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: |
        tag=$(cat version.json | jq -r ".PiliPlus")
        latest_tag=$(curl -s https://api.github.com/repos/bggRGjQaUbCoE/PiliPlus/releases/latest | jq  -r '.name')

        echo "PiliPlus version: $tag/$latest_tag"
     
        if [ "$latest_tag" != "null" ] && [ "$tag" != "$latest_tag" ]; then
          echo "PiliPlus version is outdated. Updating..."

          cat apps.json | jq --arg latest_tag "$latest_tag" '.apps = [{
            "name": "PiliPlus",
            "bundleIdentifier": "com.example.piliplus",
            "iconURL": "https://github.com/bggRGjQaUbCoE/PiliPlus/blob/main/assets/images/logo/logo.png?raw=true",
            "downloadURL": "https://github.com/bggRGjQaUbCoE/PiliPlus/releases/download/\($latest_tag)/ios-release-no-sign.ipa",
            "version": $latest_tag
          }] + .apps'  > apps.tmp
          mv apps.tmp apps.json

          cat version.json | jq --arg latest_tag "$latest_tag" '.PiliPlus= $latest_tag' > version.tmp 
          mv version.tmp version.json

        else
          echo "PiliPlus version is up to date."
        fi

        
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        if git diff --quiet; then
          echo "No changes to commit."
        else
          git add .
          git commit -m "update app"
          git push
        fi
