name: "Source Update"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        cat version.json |jq  ".dart_simple_live"
        
