name: "Source Update"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: |
        tag1=$(cat version.json | jq  ".dart_simple_live")
        tag2=$(cat version.json | jq  ".Bangumi")

        latest_tag1=$(curl -s https://api.github.com/repos/xiaoyaocz/dart_simple_live/releases/latest | jq  '.tag_name | ltrimstr("v")')
        latest_tag2=$(curl -s https://api.github.com/repos/czy0729/Bangumi/releases/latest | jq  '.tag_name | ltrimstr("v")')
        
        if [ "$tag1" != "$latest_tag1" ]; then
          echo "dart_simple_live version is outdated. Updating..."

          cat apps.json | jq --arg latest_tag1 "$latest_tag1" '.apps += [{
            "name": "dart_simple_live",
            "bundleIdentifier": "com.xycz.simple-live",
            "downloadURL": "https://github.com/xiaoyaocz/dart_simple_live/releases/download/v\($latest_tag1)/ios_no_sign.ipa",
            "version": $latest_tag1
          }]'  > apps.json

          cat version.json | jq --arg latest_tag1 "$latest_tag1" '.dart_simple_live = $latest_tag1' > version.json

        else
          echo "dart_simple_live version is up to date."
        fi

        if [ "$tag2" != "$latest_tag2" ]; then
          echo "Bangumi version is outdated. Updating..."

          latest_tag2=$(curl -s https://api.github.com/repos/czy0729/Bangumi/releases/latest | jq -r '.tag_name | ltrimstr("v")')

          url="https://github.com/czy0729/Bangumi/releases/download/${latest_tag2}/bangumi_v${latest_tag2}_archive.ipa"

          # Check if the file exists
          status_code=$(curl -o /dev/null -s -w "%{http_code}" --head "$url")

          if [ "$status_code" = "404" ]; then
              echo "❌ File does not exist"
          else
            cat apps.json | jq --arg latest_tag2 "$latest_tag2" '.apps += [{
              "name": "Bangumi",
              "bundleIdentifier": "tv.bangumi.czy0729",
              "downloadURL": "https://github.com/czy0729/Bangumi/releases/download/\($latest_tag2)/bangumi_v\($latest_tag2)_archive.ipa",
              "version": $latest_tag2
            }]'  > apps.json

            cat version.json | jq --arg latest_tag2 "$latest_tag2" '.Bangumi = $latest_tag2' > version.json
          fi

        else
          echo "Bangumi version is up to date."
        fi

        
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        if git diff --quiet; then
          echo "No changes to commit."
        else
          git add .
          git commit -m "update app"
          git push
        fi
